apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    certmanager.k8s.io/disable-validation: "true"
    kfctl.kubeflow.io/force-delete: "false"
    sidecar.istio.io/inject: "false"
  clusterName: arn:aws:eks:us-east-1:766425041025:cluster/kubeflow-ts
  creationTimestamp: null
  name: kubeflow-ts
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: namespaces/base
    name: namespaces
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-stack
    name: istio-stack
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/v3
    name: application
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller/base
    name: metacontroller
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap/overlays/application
    name: bootstrap
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: spark/spark-operator/overlays/application
    name: spark-operator
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: knative/installs/generic
    name: knative
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kfserving/installs/generic
    name: kfserving
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/spartakus
    name: spartakus
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws
    name: kubeflow-apps
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/aws/application/istio-ingress-cognito
    name: istio-ingress
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: aws/aws-istio-authz-adaptor/base_v3
    name: aws-istio-authz-adaptor
  plugins:
  - kind: KfAwsPlugin
    metadata:
      creationTimestamp: null
      name: aws
    spec:
      addons:
      - fluentd-cloud-watch
      auth:
        cognito:
          certArn: arn:aws:acm:us-east-1:766425041025:certificate/13c8f1c9-9297-4eee-8d68-3eb3041765be
          cognitoAppClientId: 1qlg2f7sagm6ob7s5985rm1qk8
          cognitoUserPoolArn: arn:aws:cognito-idp:us-east-1:766425041025:userpool/us-east-1_mg7wscVHr
          cognitoUserPoolDomain: cognito.auth.kubeflow-ts.theawsninja.com
      enablePodIamPolicy: false
      region: us-east-1
      roles:
      - kubeflow_kubeflow_Worker
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/v1.2.0.tar.gz
  version: v1.2-branch
status:
  reposCache:
  - localPath: '".cache/manifests/manifests-1.2.0"'
    name: manifests
